development:
  sessions:
    default:
      database: newer_thinking_lobster_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: newer_thinking_lobster_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      uri: <%= ENV['MONGO_URL'] %>